# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   app.file_reader:
        class:     AppBundle\Reader\FileReader
   app.patient_mapper:
        class:     AppBundle\Mapper\PatientMapper